### ISSUE TITLE
InSpec provisioner is dropping the `attributes` property

### ISSUE THREAD

**Issue by elasticdog** [mayn/packerlicious#172]
### packerlicious version

1.4.0 -> 1.4.1

### Expected behavior

The provided `attributes` property should end up in the final provisioner configuration:

```python
>>> from packerlicious import builder, provisioner, Template
>>> template = Template()
>>> template.add_provisioner(
...     provisioner.Inspec(
...         attributes=["examples/linux.yml"],
...         profile="https://github.com/dev-sec/linux-baseline"
...     )
... )
<packerlicious.provisioner.Inspec object at 0x10f75e898>
>>> print(template.to_json())
{
  "provisioners": [
    {
      "attributes": ["examples/linux.yml"],
      "profile": "https://github.com/dev-sec/linux-baseline",
      "type": "inspec"
    }
  ]
}
```

### Actual behavior

The provided `attributes` property is silently discarded in the final provisioner configuration:

```python
>>> from packerlicious import builder, provisioner, Template
>>> template = Template()
>>> template.add_provisioner(
...     provisioner.Inspec(
...         attributes=["examples/linux.yml"],
...         profile="https://github.com/dev-sec/linux-baseline"
...     )
... )
<packerlicious.provisioner.Inspec object at 0x10f75e898>
>>> print(template.to_json())
{
  "provisioners": [
    {
      "profile": "https://github.com/dev-sec/linux-baseline",
      "type": "inspec"
    }
  ]
}
```

### Steps to reproduce

See above...

**Comment by mayn** [comment]
thanks @elasticdog, [v1.4.2](https://github.com/mayn/packerlicious/releases/tag/v1.4.2) released to address this issue.

**Comment by elasticdog** [comment]
@mayn wow, thank you for the amazing turn around! I had poked around the code and didn't see anything obvious jump out at me...never would have thought that the troposphere code would cause a conflict.

**Comment by mayn** [comment]
@elasticdog yeah no problem. 
It looks like the name conflict is because of the similarities between packer and python PEP8 naming convention (use of snake_case). 

troposphere project is not affected because AWS cloudformation uses a naming convention closer to PascalCase while troposphere is snake_case. 
So the `props` definitions would never overlap the python code that is used to dynamically generate itself (they would just be set on the object as attributes using PascalCase)

Pretty cool bug.
